services:
  client:
    user: ${USER_ID}
    build:
      context: .
      dockerfile: ./client/dockerfile.dev
    ports:
      - 1234:1234
    volumes:
      - ./client/src:/client/src
      - ./client/tsconfig.json:/client/tsconfig.json
      - ./client/package.json:/client/package.json
      - ./client/package-lock.json:/client/package-lock.json
      - ./client/node_modules:/client/node_modules
    depends_on:
      - server

  server:
    user: ${USER_ID}
    build:
      context: .
      dockerfile: ./server/dockerfile.dev
    environment:
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/server/src
      - ./server/package-lock.json:/server/package-lock.json
      - ./server/package.json:/server/package.json
      - ./server/tsconfig.json:/server/tsconfig.json
      - ./server/node_modules:/server/node_modules
    depends_on:
      - db
      - storage

  nginx:
    user: ${USER_ID}
    image: nginx:1.23.1-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/dev/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server

  storage:
    user: ${USER_ID}
    image: minio/minio:RELEASE.2022-09-22T18-57-27Z
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data
    command: server /data

  initStorage:
    user: ${USER_ID}
    image: minio/mc:RELEASE.2022-10-09T21-10-59Z
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add storage http://storage:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb storage/file --ignore-existing;
      "

  db:
    user: ${USER_ID}
    image: mongo:6.0.1
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
