name: check-prettified
run-name: Checking code is prettified
on: [push]

jobs:
  check-prettified:
    strategy:
      matrix:
        path: ["client", "server"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: ${{ matrix.path }}/package-lock.json

      - run: npm ci
        working-directory: ${{ matrix.path }}

      - run: npm run format
        working-directory: ${{ matrix.path }}

      - run: |
          if [[ $(git diff --name-only) ]]; then
              echo "**'${{ matrix.path }}' is not formatted. Please run 'npm run format' before push**"
              exit 1
          fi
