name: check-api-genrated
run-name: Checking api is generated
on: [push]

jobs:
  check-api-genrated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: ./gen-api.sh
        shell: bash
        env:
          MONGO_ROOT_USERNAME: username
          MONGO_ROOT_PASSWORD: password
          JWT_SECRET: anySecretKey
          MINIO_ROOT_USER: user
          MINIO_ROOT_PASSWORD: password
          SERVER_ROOT_USER: user
          SERVER_ROOT_PASSWORD: password
          START_AT: Wed Nov 01 2022 15:29:59 GMT+0900
          END_AT: Wed Nov 02 2022 15:29:59 GMT+0900

      - run: |
          if [[ $(git diff --name-only) ]]; then
              echo "**Api is not generated. Please run './gen-api.sh' before push**"
              exit 1
          fi
